M_Network/M_Network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework import routers
from marketapp.api_views import ProductViewSet, ClientViewSet, MarketsProdsViewSet

router = routers.DefaultRouter()
router.register(r'products',ProductViewSet)
router.register(r'clients',ClientViewSet)
router.register(r'markets_prods',MarketsProdsViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('marketapp.urls', namespace='market')),
    path('users/',include('usersapp.urls',namespace='users')),
    path('api-auth/',include('rest_framework.urls')),
    path('api/v0/',include(router.urls))
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

M_Network/marketapp/urls.py
from django.urls import path
from marketapp import views

app_name = 'marketapp'

urlpatterns = [
    path('',views.main_view, name = 'index'),
    path('singin/', views.reg, name = 'signIn'),
    path('product/<int:id>', views.product, name = 'product'),
    path('product_buy/<int:product_id><int:market_id>', views.product_buy, name = 'product_buy'),
    path('shopping_cart/', views.shopping_cart, name = 'cart'),
    path('shopping_cart_change/<int:product_id>', views.change_cart, name = 'change_cart'),
    path('add_product/', views.add_product, name = 'add_prod'),
    path('orders/', views.client_orders, name = 'orders'),
    path('orders_for_manager/', views.market_orders, name = 'm_orders'),
    path('profile/', views.profile_view, name = 'profile'),
    path('buy_delivery/', views.by_with_delivery, name = 'delivery'),
    path('updatetoken/',views.update_token, name='update_token'),
]

M_Network/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView
app_name = 'usersapp'

urlpatterns = [
    path('login/',views.UserLoginView.as_view(), name = 'login'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    path('register/',views.UserCreateView.as_view(), name = 'register'),
]

M_Network/usersapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Shopper(AbstractUser):
    age = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=12,null=True, blank=True)
    market_id = models.IntegerField()

    #def save(self, *args, **kwargs):
    #    user = super().save(*args,**kwargs)
    #    if user is None:
    #    #if not Profile.objects.filter(user=user).exists():
    #        Profile.objects.create(user=user)
    #    return user

class Profile(models.Model):
    delivery_enable = models.BooleanField(default=False)
    user = models.OneToOneField(Shopper,on_delete=models.CASCADE,blank=True)
    address = models.CharField(max_length=150,null=True,blank=True)

@receiver(post_save,sender=Shopper)
def create_profile(sender,instance,**kwargs):
    print('Создан новый профиль')
    if not Profile.objects.filter(user=instance).exists():
        Profile.objects.create(user=instance)

M_Network/usersapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Shopper

class RegistrationForm(UserCreationForm):
    class Meta():
        model = Shopper
        fields = ('username','first_name','last_name','phone','market_id')

M_Network/usersapp/views.py
from rest_framework.authtoken.models import Token
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic import CreateView, DetailView
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from .forms import RegistrationForm
from .models import Shopper

# Create your views here.
class UserLoginView(LoginView):
    title = 'Вход'
    template_name = 'usersapp/login.html'

class UserCreateView(CreateView):
    model = Shopper
    template_name = 'usersapp/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('users:login')

class ProfileView(DetailView):
    model = Shopper
    template_name = 'usersapp/profile_token.html'

def update_token(requests):
    user = requests.user
    if user.auth_token:
        user.auth_token.delete()
        Token.objects.create(users=user)
    else:
        Token.objects.create(users=user)
    return HttpResponseRedirect(reverse('users:profile'))

M_Network/usersapp/templates/usersapp/login.html
{% extends "base.html" %}

{% block title %}Вход{% endblock %}

{% block products_info %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Войти</button>
    </form>
{% endblock %}

M_Network/usersapp/templates/usersapp/profile_token.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block products_info %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-10">
                    <!-- Post preview-->
                    <div>
                        Токен: {% if object.auth_token%} {{object.auth_token}} {% else %} не создан {% endif %}
                        <form action="{% url 'users:update_token' %}">
                            <button type="submit" class="btn btn-primary text-uppercase">Обновить токен</button>
                        </form>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                </div>
            </div>
{% endblock %}

M_Network/usersapp/templates/usersapp/register.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}

{% block products_info %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}