M_Network/M_Network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework import routers
from marketapp.api_views import ProductViewSet, ClientViewSet, MarketsProdsViewSet

router = routers.DefaultRouter()
router.register(r'products',ProductViewSet)
router.register(r'clients',ClientViewSet)
router.register(r'markets_prods',MarketsProdsViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('marketapp.urls', namespace='market')),
    path('users/',include('usersapp.urls',namespace='users')),
    path('api-auth/',include('rest_framework.urls')),
    path('api/v0/',include(router.urls))
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

M_Network/marketapp/urls.py
from django.urls import path
from marketapp import views

app_name = 'marketapp'

urlpatterns = [
    path('',views.main_view, name = 'index'),
    path('singin/', views.reg, name = 'signIn'),
    path('product/<int:id>', views.product, name = 'product'),
    path('product_buy/<int:product_id><int:market_id>', views.product_buy, name = 'product_buy'),
    path('shopping_cart/', views.shopping_cart, name = 'cart'),
    path('shopping_cart_change/<int:product_id>', views.change_cart, name = 'change_cart'),
    path('add_product/', views.add_product, name = 'add_prod'),
    path('orders/', views.client_orders, name = 'orders'),
    path('orders_for_manager/', views.market_orders, name = 'm_orders'),
    path('profile/', views.profile_view, name = 'profile'),
    path('buy_delivery/', views.by_with_delivery, name = 'delivery'),
    path('updatetoken/',views.update_token, name='update_token'),
]

M_Network/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView
app_name = 'usersapp'

urlpatterns = [
    path('login/',views.UserLoginView.as_view(), name = 'login'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    path('register/',views.UserCreateView.as_view(), name = 'register'),
]

M_Network/marketapp/models.py
from django.db import models
from usersapp.models import Shopper
# Create your models here.


# Create your models here.
class Clients(models.Model):
    f = models.CharField(max_length=50)
    i = models.CharField(max_length=50)
    o = models.CharField(max_length=50)
    age = models.DateField(null=True,blank=True)
    phone = models.CharField(max_length=12)
    pswrd = models.CharField(max_length=30)
    def __str__(self):
        return (self.f+' '+self.i+' '+self.o)

class Managers(models.Model):
    zp = models.IntegerField()
    pswrd = models.CharField(max_length=30)

class Top_managers(models.Model):
    zp = models.IntegerField()
    pswrd = models.CharField(max_length=30)

class Reps(models.Model):
    top_manager_id = models.ForeignKey(Top_managers, on_delete=models.CASCADE)

class Markets(models.Model):
    manager_id = models.ForeignKey(Managers, on_delete=models.CASCADE)
    id_rep = models.ForeignKey(Reps, on_delete=models.CASCADE)

class Products(models.Model):
    product_name = models.CharField(max_length=40)
    price = models.FloatField()

    def get_all(self):
        all = Products.objects.all()
        return all

    def __str__(self):
        return self.product_name

class Reps_prods(models.Model):
    rep_id = models.ForeignKey(Reps, on_delete=models.CASCADE)
    prod_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    count = models.IntegerField()

class Markets_prods(models.Model):
    market_id = models.ForeignKey(Markets, on_delete=models.CASCADE)
    prod_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    count = models.IntegerField()

    def get_all(self):
        all = Markets_prods.objects.all()
        return all

class Clients_prods(models.Model):
    client_id = models.ForeignKey(Shopper, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    market_id = models.ForeignKey(Markets, on_delete=models.CASCADE)
    pay = models.IntegerField()
    count = models.IntegerField()

    def change(self,count,user_id,product_id):
        if count == 0:
            client_product = Clients_prods.objects.get(client_id=user_id, product_id=product_id)
            client_product.delete()
            return 1
        elif count > 0:
            client_product = Clients_prods.objects.get(client_id=user_id, product_id=product_id)
            client_product.count = count
            client_product.save()
            return 2
        else:
            return 0


class Clients_orders(models.Model):
    client_id = models.ForeignKey(Shopper, on_delete=models.CASCADE)
    order_info = models.TextField()

class Orders_prods(models.Model):
    order_id = models.ForeignKey(Clients_orders, on_delete=models.CASCADE)
    prod_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    count = models.IntegerField()

M_Network/marketapp/forms.py
from django import forms
from .models import Clients, Markets_prods

class RegForm(forms.ModelForm):
    last_name = forms.CharField(label='Фамилия')
    first_name = forms.CharField(label='Имя')
    phone = forms.CharField(label='Номер телефона')
    market_id = forms.CharField(label='Ближайший магазин')
    class Meta:
        model = Clients
        #fields = '__all__'
        exclude = ('age',)

class Add_form(forms.Form):
    prod_id = forms.IntegerField(label='Индекс нового товара')
    count = forms.IntegerField(label='Количество товара')

class Form_buy(forms.Form):
    count = forms.IntegerField(label='Количество')

class Form_change(forms.Form):
    count = forms.IntegerField(label='Изменить количество')

class Form_profile(forms.Form):
    age = forms.DateField(label='Дата рождения', widget=forms.DateInput(attrs={'placeholder': 'DD.MM.YYYY'}))
    address = forms.CharField(label='Адрес', widget=forms.Textarea(attrs={'placeholder': 'Ваш адрес'}))
    phone = forms.CharField(label='Телефон',widget=forms.TextInput(attrs={'placeholder':'Ваш номер телефона'}))

M_Network/marketapp/views.py
import psycopg2
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import RegForm, Form_buy, Form_change, Add_form, Form_profile
from .models import Products, Markets_prods, Clients_prods, Markets, Clients_orders, Orders_prods
from usersapp.models import Shopper, Profile
from M_Network import settings
from rest_framework.authtoken.models import Token
# Create your views here.
def main_view(request):
    market_prods = []
    prods = []
    title = 'Ассортимент'

    if request.user.is_authenticated:
        assortiment = Markets_prods.objects.select_related('prod_id').filter(market_id=request.user.market_id)
    else:
        assortiment = Products.objects.all()

    paginator = Paginator(assortiment,3)

    page = request.GET.get('page')
    try:
        assortiment = paginator.page(page)
    except PageNotAnInteger:
        assortiment = paginator.page(1)
    except EmptyPage:
        assortiment = paginator.page(paginator.num_pages)
    #for item in assortiment:
        #print(item.)
    return render(request, 'marketapp/index.html', context={'assortiment': assortiment, 'title': title})


def reg(request):
    title = 'Регистрация'
    if request.method == 'POST':
        form = RegForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('market:index'))
        else:
            print('Not valid data')
            return render(request, 'marketapp/signin.html', context={'form': form,'title':title})
    else:
        form = RegForm()
        return render(request, 'marketapp/signin.html', context={'form': form,'title':title})

def product(request,id):
    title = 'Информация'
    product = Products.objects.get(id = id)
    return render(request,'marketapp/product.html',context = {'product_info':product,'title':title})

def product_buy(request,product_id,market_id):
    if request.user.is_staff == False:
        title = 'Покупка'
        product = Products.objects.get(id=product_id)
        if request.method == 'POST':
            form = Form_buy(request.POST)
            if form.is_valid():
                count_duplicates = len(Clients_prods.objects.filter(client_id=request.user.id, product_id=product_id))
                if count_duplicates > 0:
                    print('Нельзя создать две одинаковые позиции')
                    return HttpResponseRedirect(reverse('market:index'))
                count = form.cleaned_data['count']
                Clients_prods.objects.create(pay=0,count=count,client_id=Shopper.objects.get(id=request.user.id),market_id=Markets.objects.get(id=market_id),product_id=Products.objects.get(id=product_id))
                return HttpResponseRedirect(reverse('market:index'))
            else:
                return render(request, 'marketapp/product_buy.html', context={'product_info': product, 'form': form,'title':title})
        else:
            form = Form_buy()
            return render(request,'marketapp/product_buy.html',context = {'product_info':product,'form':form,'title':title})
    else:
        title = 'Редактирование'
        product = Products.objects.get(id=product_id)
        if request.method == 'POST':
            form = Form_change(request.POST)
            if form.is_valid():
                new_count = form.cleaned_data['count']
                if new_count > 0:
                    old_data = Markets_prods.objects.get(prod_id=product_id,market_id=request.user.market_id)
                    old_data.count = new_count
                    old_data.save()
                elif new_count == 0:
                    old_data = Markets_prods.objects.get(prod_id=product_id, market_id=request.user.market_id)
                    old_data.delete()
                return HttpResponseRedirect(reverse('market:index'))
            else:
                return render(request, 'marketapp/product_buy.html', context={'product_info': product, 'form': form,'title':title})
        else:
            form = Form_change()
            return render(request, 'marketapp/product_buy.html', context={'product_info': product, 'form': form,'title':title})

def shopping_cart(request):
    title = 'Корзина'
    products = Clients_prods.objects.select_related('product_id').filter(client_id=request.user.id)
    if request.method=='GET':
        return render(request, 'marketapp/shopping_cart.html', context={'own_cart': products,'title':title})
    else:
        try:
            connection = psycopg2.connect(
                host =settings.db_host,
                user =settings.db_user,
                password =settings.db_pswrd,
                database =settings.db_name,
                port = settings.db_port
            )
            connection.autocommit = True
            with connection.cursor() as cursor:
                cursor.execute(f'call client_buy_own_shopping_cart_products({request.user.id})')
        except Exception as _ex:
            print('Error while working with PostgreSQL', _ex)
        finally:
            return HttpResponseRedirect(reverse('market:cart'))

@user_passes_test(lambda user: user.profile.delivery_enable,login_url='/profile/')
def by_with_delivery(request):
    try:
        connection = psycopg2.connect(
            host=settings.db_host,
            user=settings.db_user,
            password=settings.db_pswrd,
            database=settings.db_name,
            port=settings.db_port
        )
        connection.autocommit = True
        with connection.cursor() as cursor:
            cursor.execute(f'call client_buy_own_shopping_cart_products({request.user.id})')
    except Exception as _ex:
        print('Error while working with PostgreSQL', _ex)
    finally:
        return render(request, 'marketapp/buy_delivery.html')


def change_cart(request,product_id):
    title = 'Редактирование'
    product = Products.objects.get(id=product_id)
    cl = Clients_prods.objects.get(client_id=request.user.id, product_id=product_id)
    if request.method == 'POST':
        form = Form_change(request.POST)
        if form.is_valid():
            count = form.cleaned_data['count']

            Clients_prods.change(count,request.user.id,product_id)

            return HttpResponseRedirect(reverse('market:cart'))
        else:
            return render(request, 'marketapp/change.html', context={'product_info': product, 'form': form,'title':title})
    else:
        form = Form_change(request.POST)
        return render(request, 'marketapp/change.html', context={'product_info': product,'count':cl.count, 'form': form,'title':title})

def add_product(request):
    title = 'Добавление'
    if request.method == 'POST':
        form = Add_form(request.POST)
        if form.is_valid():
            prod_id = form.cleaned_data['prod_id']
            count = form.cleaned_data['count']
            try:
                m_prods = Markets_prods.objects.get(market_id=request.user.market_id,prod_id=prod_id)
                if m_prods.id > 0:
                    print('Невозможно добавить дупликат товара')
                    return HttpResponseRedirect(reverse('market:index'))
            except:
                Markets_prods.objects.create(market_id=Markets.objects.get(id=request.user.market_id),prod_id=Products.objects.get(id=prod_id),count=count)
                return HttpResponseRedirect(reverse('market:index'))
        else:
            print('Not valid data')
            return render(request, 'marketapp/add_product.html', context={'form': form,'title':title})
    else:
        form = Add_form()
        return render(request, 'marketapp/add_product.html', context={'form': form,'title':title})

def client_orders(request):
    title = 'Заказы'
    orders = Clients_orders.objects.select_related('client_id').filter(client_id_id = request.user.id)
    prods = Orders_prods.objects.select_related('prod_id','order_id').all()
    for order,i in zip(orders,range(len(orders))):
        order.client_id.id = i+1
    return render(request, 'marketapp/client_orders.html', context={'client_orders': orders,'order_products':prods,'title':title})

def market_orders(request):
    title = 'Заказы'
    orders = Clients_orders.objects.select_related('client_id').all()
    return render(request, 'marketapp/orders_for_manager.html', context={'market_orders': orders,'title':title})

def profile_view(request):
    title = 'Профиль'
    address_info = Profile.objects.get(user_id=request.user.id)
    token = Token.objects.get(user=request.user)
    if request.method=='GET':
        form = Form_profile()
        return render(request, 'marketapp/profile_user.html', context={'title':title,'address':address_info.address,'form':form,'token':token})
    else:
        form = Form_profile(request.POST)
        if form.is_valid():
            new_date = form.cleaned_data['age']
            new_address = form.cleaned_data['address']
            new_phone = form.cleaned_data['phone']
            print(new_date)
            print(new_address)
            print(new_phone)
            request.user.age = new_date
            request.user.phone = new_phone
            address_info.address = new_address
            address_info.delivery_enable = True
            request.user.save()
            address_info.save()
            return HttpResponseRedirect(reverse('market:profile'))
        else:
            print('FORM is invalid')
            return render(request, 'marketapp/profile_user.html', context={'title':title,'address':address_info.address,'form':form,'token':token})

def update_token(requests):
    user = requests.user
    token = Token.objects.get(user = user)
    if token:
        token.delete()
        Token.objects.create(user=user)
    else:
        Token.objects.create(user=user)

M_Network/marketapp/templates/marketapp/add_product.html
{% extends "base.html" %}

{% block title %}Info about product{% endblock %}

{% block products_info %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    <div class="post-preview">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p}}
                            <button type="submit" class="btn btn-primary text-uppercase">Добавить</button>
                        </form>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'market:index' %}">Отмена</a></div>
                </div>
            </div>
{% endblock %}

M_Network/marketapp/templates/marketapp/buy_delivery.html
{% extends "base.html" %}

{% block title %}Корзина{% endblock %}

{% block products_info %}
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <p style="text-align:center;font-size:50px;">Вы заказали доставку на дом!</p>
    </div>
{% endblock %}

M_Network/marketapp/templates/marketapp/change.html
{% extends "base.html" %}

{% block title %}Info about product{% endblock %}

{% block products_info %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    <div class="post-preview">
                        <h2 class="post-title">{{ product_info.product_name }}</h2>
                        <h3 class="post-subtitle">{{ product_info.price }}руб</h3>
                        <h3 class="post-subtitle">{{ count }}шт</h3>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on September 24, 2022
                        </p>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p}}
                            <button type="submit" class="btn btn-primary text-uppercase">Изменить</button>
                        </form>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'market:cart' %}">Отмена</a></div>
                </div>
            </div>
{% endblock %}

M_Network/marketapp/templates/marketapp/client_orders.html
{% extends "base.html" %}

{% block title %}Заказы{% endblock %}

{% block products_info %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% for order in client_orders %}
                    <div class="post-preview">
                        <div style="display:flex; justify-content:space-between;">
                            <h2 class="post-title">№{{ order.client_id.id }}</h2>
                            <h2 class="post-title">{{ order.order_info }}</h2>
                        </div>
                        <hr class="my-4" />
                        {% for product in order_products %}
                        {% if product.order_id.id == order.id %}
                        <a href="{% url 'market:product' id=product.prod_id_id %}">
                            <h2 class="post-title" >{{product.prod_id.product_name}}</h2>
                            <h3 class="post-subtitle">{{product.prod_id.price}}руб___________________________________________{{product.count}}шт</h3>
                        </a>
                        {% endif %}
                        {% endfor%}
                        <hr class="my-4" />
                    </div>
                    <!-- Divider-->
                    {% endfor %}
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">К другим товарам →</a></div>
                </div>
            </div>
{% endblock %}

M_Network/marketapp/templates/marketapp/index.html
{% extends "base.html" %}

{% block title %}Techno Market{% endblock %}

{% block products_info %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-10">
                    <!-- Post preview-->
                        {% if user.is_authenticated %}
                            {% for item in assortiment %}
                                <div class="post-preview">
                                    <a href="{% url 'market:product_buy' product_id=item.prod_id.id market_id=user.market_id %}">
                                        <h2 class="post-title">{{ item.prod_id.product_name }}</h2>
                                        <h3 class="post-subtitle">{{ item.prod_id.price }}руб___________________________________________{{ item.count }}шт</h3>
                                    </a>
                                </div>
                            {% endfor %}
                        {% else %}
                            {% for item in assortiment %}
                                <div class="post-preview">
                                    <a href="{% url 'market:product' id=item.id %}">
                                        <h2 class="post-title">{{ item.product_name }}</h2>
                                        <h3 class="post-subtitle">{{ item.price }}руб</h3>
                                    </a>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <hr class="my-4" />
                        <!-- Pager-->
                        <div class="d-flex justify-content-space-between mb-4" style="justify-content:space-between;">
                            {% if assortiment.has_previous %}
                                <a class="btn btn-primary text-uppercase" href="?page={{ assortiment.previous_page_number }}"><На предыдущую страницу</a>
                            {% endif %}
                            <span>
                                Страница {{assortiment.number}} из {{assortiment.paginator.num_pages}}.
                            </span>
                            {% if assortiment.has_next %}
                                <a class="btn btn-primary text-uppercase" href="?page={{ assortiment.next_page_number }}">На следующую страницу></a>
                            {% endif %}
                        </div>
                        <hr class="my-4" />
                </div>
            </div>
{% endblock %}

M_Network/marketapp/templates/marketapp/orders_for_manager.html
{% extends "base.html" %}

{% block title %}Market Orders{% endblock %}

{% block products_info %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% for order in market_orders %}
                    {% if order.client_id.market_id == user.market_id %}
                    <div class="post-preview">
                        <div style="display:flex; justify-content:space-between;">
                            <h2 class="post-title">№{{ order.id }}</h2>
                            <h2 class="post-title">{{ order.order_info }}</h2>
                        </div>
                    </div>
                    <hr class="my-4" />
                    {% endif %}
                    {% endfor %}
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">К другим товарам →</a></div>
                </div>
            </div>
{% endblock %}

M_Network/marketapp/templates/marketapp/product.html
{% extends "base.html" %}

{% block title %}Info about product{% endblock %}

{% block products_info %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    <div class="post-preview">
                        <h2 class="post-title">{{ product_info.product_name }}</h2>
                        <h3 class="post-subtitle">{{ product_info.price }}руб</h3>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on September 24, 2022
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
{% endblock %}

M_Network/marketapp/templates/marketapp/product_buy.html
{% extends "base.html" %}

{% block title %}Info about product{% endblock %}

{% block products_info %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    <div class="post-preview">
                        <h2 class="post-title">{{ product_info.product_name }}</h2>
                        <h3 class="post-subtitle">{{ product_info.price }}руб</h3>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on September 24, 2022
                        </p>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p}}
                            {% if user.is_staff %}
                            <button type="submit" class="btn btn-primary text-uppercase">Изменить</button>
                            {% else %}
                            <button type="submit" class="btn btn-primary text-uppercase">Добавить в корзину</button>
                            {% endif %}
                        </form>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'market:index' %}">Отмена</a></div>
                </div>
            </div>
{% endblock %}

M_Network/marketapp/templates/marketapp/profile_user.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block products_info %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-10">
                    <!-- Post preview-->
                    {% if user.is_superuser == True %}
                    <h2 class="post-title">Топ менеджер</h2>
                    {% else %}
                        {% if user.is_staff == True %}
                        <h2 class="post-title">Менеджер</h2>
                        {% else %}
                            <h2 class="post-title">Добрый день,</h2>
                        {% endif %}
                    {% endif %}

                    <h2 class="post-title">{{user.first_name|title}} {{user.last_name|title}}</h2>
                    <div class="post-preview" style="display:flex;justify-content:center;">
                        <div>
                            {% if user.age != None %}
                            <p class="post-subtitle" style="margin:30px">Дата рожедения:{{user.age}}</p>
                            {% else %}
                            <p class="post-subtitle" style="margin:30px">Дата рожедения: _________</p>
                            {% endif %}
                            {% if address != None %}
                            <p class="post-subtitle" style="margin:30px;">Адрес:{{address}}</p>
                            {% else %}
                            <p class="post-subtitle" style="margin:30px;transform:translate(0,280px)">Адрес: __________</p>
                            {% endif %}
                            {% if user.phone != None %}
                            <p class="post-subtitle" style="margin:30px;transform:translate(0,290px)">Телефон:{{user.phone}}</p>
                            {% else %}
                            <p class="post-subtitle" style="margin:30px;transform:translate(0,290px)">Телефон: __________</p>
                            {% endif %}
                        </div>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary text-uppercase">Изменить введённые поля</button>
                        </form>
                    </div>
                    <div>
                        Токен: {% if token%} {{token}} {% else %} не создан {% endif %}
                        <form action="{% url 'market:update_token' %}">
                            <button type="submit" class="btn btn-primary text-uppercase">Обновить токен</button>
                        </form>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                </div>
            </div>
{% endblock %}

M_Network/marketapp/templates/marketapp/shopping_cart.html
{% extends "base.html" %}

{% block title %}Корзина{% endblock %}

{% block products_info %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% for item in own_cart %}
                    <div class="post-preview">
                        <a href="{% url 'market:change_cart' product_id=item.product_id.id %}">
                            <h2 class="post-title">{{ item.product_id.product_name }}</h2>
                            <h3 class="post-subtitle">{{ item.product_id.price }}руб___________________________________________{{ item.count }}шт</h3>
                        </a>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}
                    <!-- Pager-->
                    <div style="display:flex;justify-content:right;">
                        <form action="{% url 'market:delivery' %}">
                            <div class="d-flex justify-content-end mb-4">
                                <button type="submit" class="btn btn-primary text-uppercase" style="margin-right:40px">Купить с доставкой</button>
                            </div>
                        </form>
                        <form method="post">
                            {% csrf_token %}
                            <div class="d-flex justify-content-end mb-4">
                                <button type="submit" class="btn btn-primary text-uppercase" style="margin-right:40px">Купить</button>
                                <a class="btn btn-primary text-uppercase" href="{% url 'market:index' %}">
                                    В магазин →
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
{% endblock %}