M_Network/M_Network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework import routers
from marketapp.api_views import ProductViewSet, ClientViewSet, MarketsProdsViewSet

router = routers.DefaultRouter()
router.register(r'products',ProductViewSet)
router.register(r'clients',ClientViewSet)
router.register(r'markets_prods',MarketsProdsViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('marketapp.urls', namespace='market')),
    path('users/',include('usersapp.urls',namespace='users')),
    path('api-auth/',include('rest_framework.urls')),
    path('api/v0/',include(router.urls))
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

M_Network/marketapp/urls.py
from django.urls import path
from marketapp import views

app_name = 'marketapp'

urlpatterns = [
    path('',views.main_view, name = 'index'),
    path('singin/', views.reg, name = 'signIn'),
    path('product/<int:id>', views.product, name = 'product'),
    path('product_buy/<int:product_id><int:market_id>', views.product_buy, name = 'product_buy'),
    path('shopping_cart/', views.shopping_cart, name = 'cart'),
    path('shopping_cart_change/<int:product_id>', views.change_cart, name = 'change_cart'),
    path('add_product/', views.add_product, name = 'add_prod'),
    path('orders/', views.client_orders, name = 'orders'),
    path('orders_for_manager/', views.market_orders, name = 'm_orders'),
    path('profile/', views.profile_view, name = 'profile'),
    path('buy_delivery/', views.by_with_delivery, name = 'delivery'),
    path('updatetoken/',views.update_token, name='update_token'),
]

M_Network/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView
app_name = 'usersapp'

urlpatterns = [
    path('login/',views.UserLoginView.as_view(), name = 'login'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    path('register/',views.UserCreateView.as_view(), name = 'register'),
]

M_Network/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon"/><!-- href="assets/favicon.ico" /> -->
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'market:index' %}">Главная</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        {% if user.is_staff == False %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'market:index' %}">Магазин</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'market:add_prod' %}">Добавить новый товар</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'market:m_orders' %}">Заказы</a></li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        {% if user.is_staff == False %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'market:cart' %}">Корзина</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'market:orders' %}">Заказы</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'market:profile' %}">Добрый день, {{user.first_name}} {{user.last_name}}</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:login' %}">Войти</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:logout' %}">Выйти</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:register' %}">Регистрация</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead"><!-- style="background-image: url('static/assets/img/home-bg.jpg')">-->
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            {% if title|length != 0 %}
                            <h1>{{title}}</h1>
                            {% else %}
                            <h1>Techno Market</h1>
                            {% endif %}
                            <span class="subheading">Задание по курсу Базы Данных</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            {% block products_info %}{% endblock %}
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>